dcrm/dcrm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
]

dcrm/website/urls.py
from django.urls import path
from . import views

app_name = 'website' # for reverse jinja syntax

    # in order to use django form use below sign up - then signup.html use {{form}} in urlpatterns

    # {% for field in form %}
    # <div class="mb-3"
    #    {{field.label_tag}}
    #    {{field}}
    # </div>
    # {% endfor %}

    # path('signup', views.SignUpView.as_view(), name='signup'), # CBV change class to view by using as_view()

urlpatterns = [
    path('', views.home, name='home'),
    # in order to create your own form use below
    path("signup/", views.signup_user, name="signup"),
    path("record/<int:pk>", views.customer_record, name="record"),
    path("delete_record/<int:pk>", views.delete_record, name="delete_record"),
    path("add_record", views.add_record, name="add_record"),
    path("update_record/<int:pk>", views.update_record, name="update_record"),
]

dcrm/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <title>CRM</title>
</head>
<body>
    
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'website:home' %}">CRM</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">

              {% if user.is_authenticated %}
              
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'website:add_record' %}">Add Record</a>
            </li>

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'logout' %}?next=/">Logout</a>
                <!-- redirection after logout ensured with next statements as ?next=/ - / means home page -->
              </li>

              {% else %}

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'website:signup' %}?next=login">SignUp</a>
                <!-- redirection after logout ensured with next statements as ?next=/ - / means home page -->
              </li>

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login</a>
              </li>

              {% endif %}
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
    </nav>

    <br>

</body>
</html>

{% block content %}

{% endblock %}