dcrm/dcrm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
]

dcrm/website/urls.py
from django.urls import path
from . import views

app_name = 'website' # for reverse jinja syntax

    # in order to use django form use below sign up - then signup.html use {{form}} in urlpatterns

    # {% for field in form %}
    # <div class="mb-3"
    #    {{field.label_tag}}
    #    {{field}}
    # </div>
    # {% endfor %}

    # path('signup', views.SignUpView.as_view(), name='signup'), # CBV change class to view by using as_view()

urlpatterns = [
    path('', views.home, name='home'),
    # in order to create your own form use below
    path("signup/", views.signup_user, name="signup"),
    path("record/<int:pk>", views.customer_record, name="record"),
    path("delete_record/<int:pk>", views.delete_record, name="delete_record"),
    path("add_record", views.add_record, name="add_record"),
    path("update_record/<int:pk>", views.update_record, name="update_record"),
]

dcrm/website/models.py
from django.db import models

# Create your models here.


class Record(models.Model):

	#class CityChoices(models.Choices):
	#	City = ('Istanbul', 'Ankara')
		
	created_at = models.DateTimeField(auto_now_add=True)
	first_name = models.CharField(max_length=50)
	last_name =  models.CharField(max_length=50)
	email =  models.CharField(max_length=100)
	phone = models.CharField(max_length=15)
	address =  models.CharField(max_length=100)
	city =  models.CharField(max_length=50) # , choices=CityChoices.choices
	state =  models.CharField(max_length=50)
	zipcode =  models.CharField(max_length=20)

	def __str__(self):
		return(f"{self.first_name} {self.last_name}")

dcrm/website/forms.py
# In order to get username, email, password for new user we will use forms.py
# User Creation Forms of Django will be used but, for signature form we will not use {{forms}}
# SignUpForm and Class check - flatplanet/Django-CRM/website/forms.py github repository

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError
from django.utils.deconstruct import deconstructible
from .models import Record
import logging
from django.contrib.staticfiles.storage import staticfiles_storage
import os
from django.conf import settings

# logger = logging.getLogger(__name__)

text_valid_domains = staticfiles_storage.path(r'website/validdomains.txt')

with open(os.path.join(settings.STATIC_ROOT, f'{text_valid_domains}'), 'r', encoding='utf-8') as d:
     text_read = d.readlines()

VALID_DOMAINS = text_read[1]

class SignUpForm(UserCreationForm):
    email = forms.EmailField(error_messages={"required": "Please enter email"}, 
                             label='', 
                             max_length=50, 
                             min_length=13,
                             widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':f'Email min 13 characters, {VALID_DOMAINS} domains only'}))
    first_name = forms.CharField(error_messages={"required": "Please enter your name"}, 
                                 label='', 
                                 max_length=18, 
                                 min_length=3,
                                 widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name between 3 and 18 characters'}))
    last_name = forms.CharField(error_messages={"required": "Please enter your last name"}, 
                                label='', 
                                max_length=18, 
                                min_length=2,
                                widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name between 2 and 18 characters'}))
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def clean_email(self, *args, **kwargs):
        original_email = self.cleaned_data['email']
        domain = self.cleaned_data["email"].split("@")[-1]
        if domain not in VALID_DOMAINS:
            raise ValidationError("E-mail addresses from %(domain)s are not allowed.", code="invalid", params={"domain": domain})
        return original_email

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['username'].label = ''
        self.fields['username'].help_text = '<span class="form-text text-muted"><small></small></span>'
        
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].label = ''
        self.fields['password1'].help_text = '<span class="form-text text-muted"><small>Your password must contain at least 8 characters.</small></span>'
        
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = ''
        self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Please, enter the same password as before.</small></span>'



# Create Add Record Form
class AddRecordForm(forms.ModelForm):
	first_name = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"First Name", "class":"form-control"}), label="")
	last_name = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"Last Name", "class":"form-control"}), label="")
	email = forms.CharField(required=False, widget=forms.widgets.TextInput(attrs={"placeholder":"Email", "class":"form-control"}), label="")
	phone = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"Phone", "class":"form-control"}), label="")
	address = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"Address", "class":"form-control"}), label="")
	city = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"City", "class":"form-control"}), label="")
	state = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"State", "class":"form-control"}), label="")
	zipcode = forms.CharField(required=False, widget=forms.widgets.TextInput(attrs={"placeholder":"Zipcode", "class":"form-control"}), label="")

	class Meta:
		model = Record
		exclude = ("user",)

    
class RecordNameFilterForm(forms.ModelForm):
     first_name = forms.CharField(required=False, widget=forms.widgets.TextInput(attrs={"placeholder":"First Name", "class":"form-control"}), label="")

     class Meta:
        model = Record
        exclude = ("user",)

dcrm/website/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse, reverse_lazy
from .forms import SignUpForm, AddRecordForm, RecordNameFilterForm
from .models import Record
from .filters import RecordFilter

# Create your views here.

#@login_required(login_url="/accounts/login/") # login_requierd, if not login redirect to login page
"""def home(request):
    records = Record.objects.all()
    return render(request, 'website/home.html', {'records':records})"""

@login_required(login_url="/accounts/login/") # login_requierd, if not login redirect to login page
def home(request):
    record_filter = RecordFilter(request.GET, queryset=Record.objects.all())
    context = {
        'form' : record_filter.form,
        'records' : record_filter.qs
    }
    return render(request, 'website/home.html', context)

# Creation of user Model class based view
# class SignUpView(CreateView): # inherited from CreateView
#    form_class = UserCreationForm
#    # success_url = reverse("login") reverse will work each time, instead use reverse_lazy
#    success_url = reverse_lazy("login") # reverse_lazy will work if reached
#    template_name = "registration/signup.html"

def logout_user(request):
    logout(request)
    messages.success(request, "You have been logout")
    return redirect("login")

def signup_user(request):

    if request.POST:
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            # Authenticate
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username = username, password = password)
            login(request, user)
            messages.success(request, f'You have been succesfully Registered. Welcome {user.username}')
            return redirect("website:home")
    else:
        form = SignUpForm()
        # return render(request, 'registration/signup.html', {'form': form})
    return render(request, 'registration/signup.html', {'form': form})

def customer_record(request, pk):
    if request.user.is_authenticated:
            # Look Up Records
        customer_record = Record.objects.get(id=pk)
        return render(request, 'website/record.html', {'customer_record':customer_record})
    else:
        messages.success(request, "You Must Be Logged In To View That Page...")
        return redirect('website:home')
    
def delete_record(request, pk):
    if request.user.is_authenticated:
        delete_it = Record.objects.get(id=pk)
        delete_it.delete()
        messages.success(request, f'You have deleted the customer with id: {pk}')
        return redirect("website:home")
    else:
        messages.success(request, f'You must be logged in!')
        return redirect("website:home")
    
def add_record(request):
    form = AddRecordForm(request.POST or None)
    if request.user.is_authenticated:
        if request.POST:
            if form.is_valid():
                add_record = form.save()
                messages.success(request, 'Record Added.')
                return redirect('website:home')
        return render(request, 'website/add_record.html', {'form': form})
    else:
        messages.success(request, 'You must be logged in!')
        return redirect("website:home")
    
def update_record(request, pk):
    if request.user.is_authenticated:
        current_record = Record.objects.get(id=pk)
        form = AddRecordForm(request.POST or None, instance=current_record)
        if form.is_valid():
            form.save()
            messages.success(request, 'Form has been updated.')
            return redirect("website:home")
        return render(request, 'website/update_record.html', {'form': form})
    else:
        messages.success(request, 'You must be logged in!')
        return redirect("website:home")
    
    
# RecordNameFilterForm is at forms.py - RecordFilter is at filters.py

def records_filter(request):
    first_name = request.GET.get('first_name')
    records = Record.objects.all()
    if first_name:
        records = records.filter(first_name__icontains=first_name)
    context = {
        'form' : RecordNameFilterForm(),
        'records' : records
    }
    return render(request, 'website:home', context)

dcrm/website/templates/website/add_record.html
{% extends "base.html" %}

{% block content %}

<div class="col-md-6 offset-md-3">
    <h1>Add Record</h1>
    <br/>
    
    <form method="POST" action="{% url 'website:add_record' %}">
        {% csrf_token %}
    
        {{ form.as_p }}

        <br/>
    <button type="submit" class="btn btn-danger">Add Record</button>
    <a href="{% url 'website:home' %}" class="btn btn-secondary">Back</a>

    </form>  

</div>

{% endblock %}

dcrm/website/templates/website/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <style>
      table.center {
        margin-left: auto; 
        margin-right: auto;
      }
      th, td {
        padding-left: 1px;
      }
      .card {
        margin: 2 auto; /* Added */
        float: none; /* Added */
        margin-bottom: 10px; /* Added */
      }
      .form { 
        margin: 5 auto; 
        width: 250px;
        text-align: center;
      }
      .vertical-center {
        margin: 2;
        position: absolute;
        top: 50%;
        left: 115%;
        -ms-transform: translateY(-50%);
        transform: translateY(-50%);
      }
      .container {
        height: 100px;
        position: relative;
        border: 1px solid green;
      } 
    </style>
</head>
<body>
  <div class="container">
  <div class="col-md-6 offset-md-3">
  <div class="card" style="width: 48rem;">
  <form method="GET" action="{% url 'website:home' %}" 
        style="justify-content:center; display: inline-flex; padding: 0px;">
    
    {{ form.as_p }}
    
    <div class="vertical-center">
      <input type="submit" value="Search" class="btn btn-secondary"/>
    </div>
  </form>
  </div>
  </div>
  </div>
  
  <hr/>
      <table class="table table-striped table-hover table-bordered center" style="width:90%">
        <thead class="table-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Phone</th>
            <!--<th scope="col">Address</th>-->
            <th scope="col">City</th>
            <!--<th scope="col">State</th>-->
            <!--<th scope="col">Zipcode</th>-->
            <!--<th scope="col">Created At</th>-->
            <!--<th scope="col">ID</th>-->
          </tr>
        </thead>
        <tbody>
          
      {% if records %}
        {% for record in records %}
          <tr>
            <td><a href="{% url 'website:record' record.id %}">
              {{ record.first_name }} {{ record.last_name }}</a></td>
            <td>{{ record.email }}</td>
            <td>{{ record.phone }}</td>
            <!--<td>{{ record.address }}</td>-->
            <td>{{ record.city }}</td>
            <!--<td>{{ record.state }}</td>-->
            <!--<td>{{ record.zipcode }}</td>-->
            <!--<td>{{ record.created_at }}</td>-->
            <!--<td><a href="{% url 'website:record' record.id %}">{{ record.id }}</a></td>-->
          </tr>
        {% endfor %}
      
      {% endif %}
      
        
        </tbody>
    </table>
</body>
</html>

{% endblock %}

dcrm/website/templates/website/record.html
{% extends "base.html" %}

{% block content %}

<div class="col-md-6 offset-md-3">
<div class="card">
    <div class="card-header"><strong>
          {{ customer_record.first_name }} 
          {{ customer_record.last_name }}</strong>
    </div>
    <div class="card-body">
  
  
  
  <p class="card-text">
  <strong>Email: </strong>{{ customer_record.email }}</p>
  
  <p class="card-text">
  <strong>Phone: </strong>{{ customer_record.phone }}
  </p>
  
  <p class="card-text">
  <strong>Address: </strong>{{ customer_record.address }}</p>
  
  <p class="card-text">
  <strong>City: </strong>{{ customer_record.city }}</p>
  
  <p class="card-text">
  <strong>State: </strong>{{ customer_record.state }}</p>
  
  <p class="card-text">
  <strong>Zipcode: </strong>{{ customer_record.zipcode }}</p>
  
  <p class="card-text">
  <strong>Create At: </strong>{{ customer_record.created_at }}</p>
  
  <p class="card-text">
  <strong>ID: </strong>{{ customer_record.id }}</p>
      
      
    </div>
  </div>
  
  <br/><br/>
  <a href="{% url 'website:home' %}" class="btn btn-secondary">Back</a>
  <a href="{% url 'website:update_record' customer_record.id %}" class="btn btn-secondary">Update Record</a>
  <a href="{% url 'website:delete_record' customer_record.id %}" class="btn btn-danger">Delete</a>

</div>

{% endblock %}

dcrm/website/templates/website/update_record.html
{% extends "base.html" %}

{% block content %}

<div class="col-md-6 offset-md-3">
    <h1>Update Record</h1>
    <br/>
    
    <form method="POST" action="">
        {% csrf_token %}
    
        {{ form.as_p }}

        <br/>
    <button type="submit" class="btn btn-danger">Update Record</button>
    <a href="{% url 'website:home' %}" class="btn btn-secondary">Home</a>

    </form>  

</div>

{% endblock %}